title: Faisal Adhisthana Nugraha # your name (or website title) here
logo: <img src="/Image/FOTO Biru.png" width: 200 px height: 299 px> # your photo (or logo) here images/logo.png?raw=true
description: > # your text below (remove <br> elements if you don't need line breaks)
  <p align="justify"> XXXXX I graduated Master's Degree at Institute of Technology Bandung majoring in business administration also Bachelor's Degree at Institute Technology Sepuluh Nopember majoring in Electrical Engineering. </p>   
  
  <p align="justify"> Experience in strategic planning, solving supply chain operation problems, and collaboration with cross-functional teams also strategic level position. </p>
  
  <p align="justify"> I am looking for the next step in my career through my experience in data science. If you have an opportunity to work or collaborate together, please contact me at <b>faisal.adhisthana@gmail.com</b>  . </p> 
  <br>
  <a href=" https://www.linkedin.com/in/faisal-adhisthana-nugraha-111503125/ ">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-8V4T0JCWLK # your Google Analytics tracking ID here

