title: <p align="center"> Faisal Adhisthana Nugraha, S.T., M.B.A </p> # your name (or website title) here
logo: <p align="center"> " Image/New_Foto_Faisal.png " </p> # your photo (or logo) here width: 200 px height: 299 px 
description: > # your text below (remove <br> elements if you don't need line breaks)
  <p align="justify"> I graduated Master's Degree at Institute of Technology Bandung also Bachelor's Degree at Institute Technology Sepuluh Nopember. </p> 
  <p align="justify"> I am looking for the next step in my career through my experience in data science. If you have an opportunity to work or collaborate together, please contact me at: </p> 
  
  <a href=" https://www.linkedin.com/in/faisal-adhisthana-nugraha-111503125/ ">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-8V4T0JCWLK # your Google Analytics tracking ID here

